# Generated by Django 3.2.4 on 2021-07-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptask',
            options={'verbose_name': 'Group task', 'verbose_name_plural': 'Group tasks'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
