# Generated by Django 3.2.4 on 2021-07-12 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do', '0002_auto_20210711_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='task',
            field=models.ManyToManyField(related_name='tasks', to='to_do.Task'),
        ),
        migrations.AlterField(
            model_name='grouptask',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('TD', 'To do'), ('IP', 'In progress'), ('ED', 'Finalized')], default='TD', max_length=2, verbose_name='state'),
        ),
    ]
